# 使用 Node.js 作为基础镜像
FROM node:18


# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 到工作目录
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制前端项目的所有文件到工作目录
COPY . .

# 暴露端口
EXPOSE 5173

# 运行 Vue 项目
CMD [ "npm", "run", "serve" ]
