# 使用 OpenJDK 作为基础镜像
FROM openjdk:17-jdk-slim


# 设置工作目录
WORKDIR /app

# 复制后端项目的 pom.xml 到工作目录
COPY pom.xml .

# 下载依赖
RUN apt-get update && apt-get install -y maven
RUN mvn dependency:go-offline

# 复制后端项目的所有文件到工作目录
COPY . .

# 构建项目
RUN mvn clean package -DskipTests

# 暴露端口
EXPOSE 8080

# 启动 Spring Boot 应用
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]